name: Build and deploy Python app to Azure Web App - healthappbuilderapi

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      COSMOS_DB_URL:
        description: 'Cosmos DB URL'
        required: true
      COSMOS_DB_KEY:
        description: 'Cosmos DB Key'
        required: true
      DATABASE_NAME:
        description: 'Database Name'
        required: true
      CONTAINER_NAME:
        description: 'Container Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1000B0CB69084A4E8C4A27091D200B8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94C1A1FADC9A43DE834353D45E09DB4A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70E82FD37B4E47DFB4E12E3A9B5EA6FE }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'healthappbuilderapi'
          slot-name: 'Production'

      - name: 'Configure App Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'healthappbuilderapi'
          app-settings-json: |
            [
              { "name": "COSMOS_DB_URL", "value": "${{ github.event.inputs.COSMOS_DB_URL }}" },
              { "name": "COSMOS_DB_KEY", "value": "${{ github.event.inputs.COSMOS_DB_KEY }}" },
              { "name": "DATABASE_NAME", "value": "${{ github.event.inputs.DATABASE_NAME }}" },
              { "name": "CONTAINER_NAME", "value": "${{ github.event.inputs.CONTAINER_NAME }}" },
              { "name": "AUTH0_DOMAIN", "value": "${{ secrets.AUTH0_DOMAIN }}" },
              { "name": "AUTH0_M2M_CLIENT_ID", "value": "${{ secrets.AUTH0_M2M_CLIENT_ID }}" },
              { "name": "AUTH0_M2M_CLIENT_SECRET", "value": "${{ secrets.AUTH0_M2M_CLIENT_SECRET }}" },
              { "name": "AUTH0_CONNECTION_ID", "value": "${{ secrets.AUTH0_CONNECTION_ID }}" },
              { "name": "GITHUB_PAT", "value": "${{ secrets.APP_PAT }}" },
              { "name": "GITHUB_OWNER", "value": "${{ secrets.APP_OWNER }}" },
              { "name": "WEBSITES_PORT", "value": "5000" }
            ]
