# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - healthappbuilderapi

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      COSMOS_DB_URL:
        description: 'Cosmos DB URL'
        required: true
      COSMOS_DB_KEY:
        description: 'Cosmos DB Key'
        required: true
      DATABASE_NAME:
        description: 'Database Name'
        required: true
      CONTAINER_NAME:
        description: 'Container Name'
        required: true
      AUTH0_DOMAIN:
        description: 'Auth0 Domain'
        required: true
      AUTH0_M2M_CLIENT_ID:
        description: 'Auth0 Client ID'
        required: true
      AUTH0_M2M_CLIENT_SECRET:
        description: 'Auth0 Client Secret'
        required: true
      AUTH0_CONNECTION_ID:
        description: 'Auth0 Connection ID'
        required: true
      GITHUB_PAT:
        description: 'GitHub PAT'
        required: true
      GITHUB_OWNER:
        description: 'GitHub Owner'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1000B0CB69084A4E8C4A27091D200B8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94C1A1FADC9A43DE834353D45E09DB4A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70E82FD37B4E47DFB4E12E3A9B5EA6FE }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'healthappbuilderapi'
          slot-name: 'Production'
          app-settings: |
            [
              "COSMOS_DB_URL=${{ github.event.inputs.COSMOS_DB_URL }}",
              "COSMOS_DB_KEY=${{ github.event.inputs.COSMOS_DB_KEY }}",
              "DATABASE_NAME=${{ github.event.inputs.DATABASE_NAME }}",
              "CONTAINER_NAME=${{ github.event.inputs.CONTAINER_NAME }}",
              "AUTH0_DOMAIN=${{ github.event.inputs.AUTH0_DOMAIN }}",
              "AUTH0_M2M_CLIENT_ID=${{ github.event.inputs.AUTH0_M2M_CLIENT_ID }}",
              "AUTH0_M2M_CLIENT_SECRET=${{ github.event.inputs.AUTH0_M2M_CLIENT_SECRET }}",
              "AUTH0_CONNECTION_ID=${{ github.event.inputs.AUTH0_CONNECTION_ID }}",
              "GITHUB_PAT=${{ github.event.inputs.GITHUB_PAT }}",
              "GITHUB_OWNER=${{ github.event.inputs.GITHUB_OWNER }}"
            ]
